### ISSUE TITLE
[landscape] quickly improve create new pebble form UX

### ISSUE THREAD

**Issue by danieleguido** [C2DH/memorial#37]
- [ ] move the camera in the new position already as soon as the form is visible, with a placeholder as in #34 (@wdobry ?)
- [ ] leave color of the pebble when they're note active?
- [x] fix issue #33 when the form is not in focus, we lose it forever
- [x] remove scrolling temporarily when creating a pebble
- [ ] fix issue #31 add a contextual help / reminder with basic information on how to add a pebble (read a story-> click on the create a pebble button)
- [x] fix issue #36 with a a series of button :)
